language: node_js
node_js:
- 11.1.0
deploy:
  provider: script
  script: bash ./deploy.sh
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_bfd2d857407e_key -iv $encrypted_bfd2d857407e_iv
  -in .travis/travis.key.enc -out .travis/travis.key -d
- chmod +x ./deploy.sh
- eval "$(ssh-agent -s)"
- chmod 600 .travis/travis.key
- ssh-add .travis/travis.key
- ssh-keyscan 142.93.0.148 >> ~/.ssh/known_hosts
- git remote add dokku dokku@142.93.0.148:youl
- git config --global push.default simple
script:
- yarn
- yarn build
cache: yarn
notifications:
  email: false
  webhooks:
    urls:
      secure: avhaLJsrWMthlYm6cn7OitblESMy1loiBmcTcqMKpqZijh6mnWYouM2j1OraK+uDewL5y1324S1rUOZ6gkZj3Dn7dgrZiFAJPmurbHJLLoSRZhtoymjxUyYqsdVWGqYt9KKXqBbVXGddZVYf8lkYEgNnjVRPg0+GX+w/TMnj6BIO3LNcpgEl+ZacxXH9XlLSIKPOvLoOWSe/73/HBKS/27kldmbwWgF5wM7mdtGSQvLSjl+rf3gNcHdkEuLL32C3xqQa8/7O/AynwEKO2aAP3QawuDe5BSx46uG63pEk+Bt2pAd1RyuAbh8LpCXqaSlO9d/D4XzD5RhpMEdDxoEd+pKGpTHYJrBGQFKS7wPB/2z2i6AfePsjlWv+t/O+YWwrVOA19ucfgmRjeKRm3fOkh5JSddYt+7mQJduogRMs4S0ra8/NKFCrzmmWegoi46LwOBDbpSRv2rG8hn2FUy/dPrwoo5wi2jipQbDaVHppmF3x61dpv880TyImxKeaEn4xn3Q9K5KhpoYFwmsQtdQ3DfW0SxRnzVItGV1BWwu17txABt1yHKdHvgUfg9K/Mzq9XM8HBB4pxVxGW1SS1qvMdLJyq2Ue4Ba3nmbqvPUIAH6t4lkxjnFuy7lMof1bLUZTcnQr5IpfrzD1kDCgKyMds+JZzmThuko8ezSd5BQpBmE=
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
